spring:
  application:
    name: locacao
  config:
    import: optional:file:.env.properties[.properties]

    # JPA
  jpa:
    show-sql: true
    format_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}

  # Porta e prefixo da aplicação
server:
  #port: 8085
  servlet:
    context-path: /api
