UPDATE TABLE TB_CLIENT (
    ID INTEGER(5) PRIMARY KEY AUTO_INCREMENT,
    CPF CHAR(11) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CNH CHAR(11) NOT NULL,
    IDADE DATE NOT NULL,
    NUMERO_DE_TELEFONE VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TESTE VARCHAR(50) NOT NULL
);

CREATE TABLE TB_CAR (
    ID INTEGER(5) PRIMARY KEY AUTO_INCREMENT,
    PLACA CHAR(7) NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(50) NOT NULL,
    ANO CHAR(4) NOT NULL,
    TAXA_DIARIA DECIMAL(10, 2) NOT NULL,
    TIPO_DO_MOTOR VARCHAR(50) NOT NULL
);

CREATE TABLE TB_ENDERECO(
    ID INTEGER(5) PRIMARY KEY AUTO_INCREMENT,
    CEP CHAR(8) NOT NULL,
    RUA VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(5) NOT NULL,
    BAIRRO VARCHAR(50) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    ESTADO VARCHAR(50) NOT NULL
);